### ISSUE TITLE
pod-split-up-scheduling.html   这个没有呀？是否还更新

### ISSUE THREAD

**Issue by charnet1019** [imroc/kubernetes-guide#100]

**Comment by imroc** [comment]
在这里： https://imroc.cc/kubernetes/best-practices/ha/pod-split-up-scheduling.html

**Comment by charnet1019** [comment]
https://imroc.cc/kubernetes/best-practices/ops/securely-maintain-or-offline-node.html  这篇文章中的引用地址不对，收到多谢

**Comment by imroc** [comment]
好的，我修改下
